Events: [ 
  `catalog:changed`,
  `buyerInfo:update`,
  `basket:open`,
  `basket:confirm`,
  `basket:changed`,
  `product:select`,
  `selectedProduct:changed`,
  `product:addToBasket`,
  `product:deleteFromBasket`,
  `paymentButton:card`,
  `paymentButton:cash`,
  `input:input`,
  `orderButton:next`,
  `orderSuccess:close`,
]
